# cbapi:
#     resource: "@CBAPIBundle/Resources/config/routing.yml"
#     prefix: /api
#     type: rest

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

cb_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: CentralOAuthBundle:Security:login }

cb_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: CentralOAuthBundle:Security:loginCheck }
