security:
    # encoders:
    #     CB\APIBundle\Entity\Users:
    #         algorithm:        sha1
    #         encode_as_base64: false
    #         iterations:       1
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        # user_provider:
        #     id: platform.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    #     login:
    #         pattern:  ^/demo/secured/login$
    #         security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

    #     secured_area:
    #         pattern:    ^/demo/secured/
    #         form_login:
    #             provider: user_provider
    #             check_path: _security_check
    #             login_path: _demo_login
    #         logout:
    #             path:   _demo_logout
    #             target: _demo
    #         #anonymous: ~
    #         #http_basic:
    #         #    realm: "Secured Demo Area"

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: cb_oauth_server_auth_login_check
                login_path: cb_oauth_server_auth_login
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:      true
            anonymous:   true

    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
