parameters:
#    central_o_auth.example.class: Central\OAuthBundle\Example

services:
#    central_o_auth.example:
#        class: %central_o_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
